//
// Copyright (c) 2026 Hiroshi Kimura(Muukii) <muukii.app@gmail.com>
//

import CoreImage
import CoreMedia
import Foundation

/// Overlays procedural film grain on an already graded frame.
///
/// The grain is generated by the `filmGrain` Metal Core Image kernel
/// (`FilmGrainKernels.metal`): band-limited value noise whose clumps follow a
/// height-proportional pitch, shaped by a negative-film luminance response and
/// composited additively in gamma-encoded space. Each frame samples a
/// different noise region selected by hashing the frame's composition time, so
/// playback "boils" while preview and export render identical grain for the
/// same frame time.
nonisolated enum FilmGrainRenderer {

  /// The peak grain amplitude in the gamma-encoded domain at
  /// `intensity == 100`, applied where the luminance response peaks.
  private static let maximumAmplitude: CGFloat = 0.25

  /// How far the per-channel noise deviates from shared luma noise.
  ///
  /// Real color-negative grain lives in three dye layers, so a small
  /// decorrelation reads as organic texture; full decorrelation reads as
  /// digital sensor noise.
  private static let chromaAmount: CGFloat = 0.25

  /// The grain pitch bounds as fractions of the render height.
  ///
  /// At `size == 50` a 4K export renders roughly a three-pixel clump
  /// diameter, which reads as fine photographic grain.
  private static let minimumPitchFraction: CGFloat = 0.0005
  private static let maximumPitchFraction: CGFloat = 0.0025

  /// Composites time-seeded film grain over one graded frame.
  ///
  /// The kernel runs between a `CILinearToSRGBToneCurve` /
  /// `CISRGBToneCurveToLinear` pair so its luminance response and amplitude
  /// are defined on display-referred values; the round trip returns to the
  /// linear working space expected by the composition's final render. The
  /// kernel leaves pure black and pure white untouched, so the sandwich
  /// cannot shift the graded image's color where there is no grain.
  static func apply(
    to image: CIImage,
    renderExtent: CGRect,
    compositionTime: CMTime,
    intensity: Int,
    size: Int
  ) throws -> CIImage {
    let kernel = try FilmGrainKernelStore.colorKernel()
    let fieldOffset = noiseFieldOffset(for: compositionTime)
    guard
      let grainedImage = kernel.apply(
        extent: renderExtent,
        arguments: [
          image.applyingFilter("CILinearToSRGBToneCurve"),
          grainPitch(renderHeight: renderExtent.height, size: size),
          amplitude(intensity: intensity),
          chromaAmount,
          CIVector(x: fieldOffset.x, y: fieldOffset.y),
        ]
      )
    else {
      throw FilmGrainRendererError.cannotApplyKernel
    }
    return grainedImage
      .applyingFilter("CISRGBToneCurveToLinear")
      .cropped(to: renderExtent)
  }

  /// The peak grain amplitude in the gamma-encoded domain.
  static func amplitude(intensity: Int) -> CGFloat {
    CGFloat(intensity) / 100 * maximumAmplitude
  }

  /// The rendered diameter of one grain clump in output pixels.
  ///
  /// Height-proportional scaling keeps preview and export texture identical
  /// because the preview target is a uniform fit of the export resolution.
  /// The one-pixel floor prevents sub-pixel noise from aliasing at very small
  /// preview targets.
  static func grainPitch(renderHeight: CGFloat, size: Int) -> CGFloat {
    let normalized = CGFloat(size) / 100
    let fraction =
      minimumPitchFraction
      + (maximumPitchFraction - minimumPitchFraction) * normalized
    return max(1, renderHeight * fraction)
  }

  /// Selects the noise region sampled by one frame.
  ///
  /// The composition time is quantized to a 240 Hz grid, which separates every
  /// common frame cadence while remaining identical between preview and export
  /// renders of the same frame. Offsets stay within 2048 pixels so lattice
  /// coordinates keep full float precision inside the kernel's hash.
  static func noiseFieldOffset(for time: CMTime) -> CGPoint {
    let seconds = time.seconds
    guard seconds.isFinite else {
      return .zero
    }
    let ticks = Int64((seconds * 240).rounded())
    let hash = splitmix64(UInt64(bitPattern: ticks))
    return CGPoint(
      x: CGFloat(hash & 0x7FF),
      y: CGFloat((hash >> 16) & 0x7FF)
    )
  }

  private static func splitmix64(_ value: UInt64) -> UInt64 {
    var z = value &+ 0x9E37_79B9_7F4A_7C15
    z = (z ^ (z >> 30)) &* 0xBF58_476D_1CE4_E5B9
    z = (z ^ (z >> 27)) &* 0x94D0_49BB_1331_11EB
    return z ^ (z >> 31)
  }
}

/// Errors raised while preparing or applying the film-grain kernel.
nonisolated enum FilmGrainRendererError: LocalizedError {
  case missingKernelLibrary
  case cannotLoadKernel(String)
  case cannotApplyKernel

  var errorDescription: String? {
    switch self {
    case .missingKernelLibrary:
      return "Färg couldn't find its compiled film-grain Metal library."
    case .cannotLoadKernel(let underlying):
      return "Färg couldn't load the film-grain kernel: \(underlying)"
    case .cannotApplyKernel:
      return "Färg couldn't render the film-grain overlay."
    }
  }
}

/// Loads the `filmGrain` kernel from the app's compiled Metal library once.
///
/// The kernel uses `[[ stitchable ]]`, so the ordinary Metal build step
/// produces a loadable `default.metallib` without Core Image-specific
/// compiler flags — the same packaging BrightroomParametric uses.
private nonisolated enum FilmGrainKernelStore {

  static func colorKernel() throws -> CIColorKernel {
    switch loadedKernel {
    case .success(let kernel):
      return kernel
    case .failure(let error):
      throw error
    }
  }

  private static let loadedKernel: Result<CIColorKernel, FilmGrainRendererError> = {
    guard
      let url = Bundle.main.url(
        forResource: "default",
        withExtension: "metallib"
      ),
      let data = try? Data(contentsOf: url)
    else {
      return .failure(.missingKernelLibrary)
    }
    do {
      let kernel = try CIColorKernel(
        functionName: "filmGrain",
        fromMetalLibraryData: data
      )
      return .success(kernel)
    } catch {
      return .failure(.cannotLoadKernel(String(describing: error)))
    }
  }()
}
